"""Tests for AI commit detection engine."""

from unittest.mock import MagicMock
from datetime import datetime, timezone

from git_forensic.detector import detect_commit, extract_ai_model


def _make_commit(message: str, author: str = "dev") -> MagicMock:
    commit = MagicMock()
    commit.message = message
    commit.hexsha = "abc1234567890"
    commit.author = author
    commit.authored_datetime = datetime(2026, 3, 1, tzinfo=timezone.utc)
    commit.stats.total = {"files": 3, "insertions": 50, "deletions": 10}
    return commit


class TestExtractAIModel:
    def test_claude_opus(self):
        assert extract_ai_model("Co-Authored-By: Claude Opus 4.6") == "Claude Opus"

    def test_claude_sonnet(self):
        assert extract_ai_model("Co-Authored-By: Claude Sonnet 4.6") == "Claude Sonnet"

    def test_copilot(self):
        assert extract_ai_model("Generated by Copilot") == "Copilot"

    def test_unknown(self):
        assert extract_ai_model("normal commit message") == "unknown"


class TestDetectCommit:
    def test_claude_coauthor_high_confidence(self):
        commit = _make_commit(
            "feat: add login\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>"
        )
        result = detect_commit(commit)
        assert result.is_ai
        assert result.confidence >= 0.9
        assert result.ai_model == "Claude Opus"
        assert "Claude Co-Author" in result.signals

    def test_generated_by_tag(self):
        commit = _make_commit("fix: update styles\n\nGenerated by Claude")
        result = detect_commit(commit)
        assert result.is_ai
        assert result.confidence >= 0.8

    def test_normal_commit_low_confidence(self):
        commit = _make_commit("updated readme")
        result = detect_commit(commit)
        assert not result.is_ai
        assert result.confidence < 0.5

    def test_conventional_commit_heuristic(self):
        commit = _make_commit("feat(auth): add OAuth2 provider")
        result = detect_commit(commit)
        # Heuristic only → below threshold
        assert result.confidence < 0.5

    def test_stats_extraction(self):
        commit = _make_commit("fix: bug\n\nCo-Authored-By: Claude")
        result = detect_commit(commit)
        assert result.files_changed == 3
        assert result.insertions == 50
        assert result.deletions == 10
